project: "DLF_A2"
SEED: 42
model:
  encoder:
    name: "resnet34"
    pretrained: True
    freeze_encoder: False
    drop_rate: 0.5
  triplet:
    use: False # if False, following params will not be unused.
    skip_connection: False
    positional_encoding: False
    multi_head_attention: False
    distance: "cos" # cos, l2
train:
  epochs: 50
  accelerator: gpu
  devices: 1
  ddp: False
  precision: 16-mixed
  accumulate_grad_batches: 1
  swa: 
    use: False # if False, next param will not be used; if True, conflict with "user-defined optimizer"
    swa_lr: 1e-3
  optimizer:
    auto_lr_finder: True # if True, next param will not be used
    lr: 1e-3
    weight_decay: 1e-7
  scheduler:
    T_0: 5
    T_mult: 2
    eta_min: 1e-9
data:
  dataset:
    csv_path: "data/mushrooms.csv"
    label_map: "data/mushrooms/mushrooms.txt"
    image_size: 224
    transform: True
  dataloader:
    batch_size: 64
    num_workers: 4